[package]
name = "local-recon"
version = "0.1.0"
edition = "2021"

[dependencies]
tasklist = "0.2.15"
windows = { version = "0.58.0", features = ["Win32_Foundation", "Win32_System_SystemServices", "Win32_NetworkManagement", "Win32_System_Services"] }
get_if_addrs = "0.5"
colored = "2.1.0"
