[package]
name = "dir-bruteforcer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5.17", features = ["derive"] }
reqwest = "0.12.7"
colored = "2.1.0"
futures = "0.3.30"
